all:
  children:
    haproxy:
      hosts:
        node-1:
        node-2:
  vars:
    haproxy_install_path: /usr/local/haproxy
    haproxy_parent_src_dir: /tmp
    haproxy_major_ver: 1.8
    haproxy_minor_ver : 3
    haproxy_ver : "{{haproxy_major_ver}}.{{haproxy_minor_ver}}"
    haproxy_name : "haproxy-{{haproxy_ver}}"
    haproxy_tgz : '{{haproxy_name}}.tar.gz'
    haproxy_url : '{{haproxy_mirror}}/{{haproxy_major_ver}}/src/{{haproxy_tgz}}'
    haproxy_src_dir: '{{haproxy_parent_src_dir}}/{{haproxy_name}}'